/**
 * Re-export DB row types for server components and services.
 * Prefer narrowing selects with `Pick<>` / Zod at API boundaries.
 */
export type {
  AppointmentRow,
  AppointmentChangeRequestRow,
  ClientIncidentRow,
  ClientProgramDayExerciseRow,
  ClientProgramDayRow,
  ClientSessionNoteRow,
  ClientProgramWeekRow,
  ClientAssessmentRow,
  ClientGoalRow,
  ClientMembershipPeriodRow,
  ClientProgramRow,
  ClientTrainingPreferencesRow,
  EmergencyContactRow,
  EntitlementLedgerEntryRow,
  ExerciseAlternativeRow,
  ExerciseProgressionRow,
  ExerciseRegressionRow,
  ExerciseRow,
  FinancialDocumentRow,
  GymLocationRow,
  InvoiceRow,
  MembershipTypeRow,
  PaymentRecordRow,
  ProfileRow,
  ProgressPhotoRow,
  ProgramChangeRequestRow,
  ProgramTemplateDayExerciseRow,
  ProgramTemplateDayRow,
  ProgramTemplateRow,
  ProgramTemplateWeekRow,
  ReceiptRow,
  StaffNoteRow,
  StaffShiftRow,
  TrainerAvailabilitySlotRow,
  TrainerClientAssignmentRow,
  WorkoutSessionRow,
  WorkoutSessionExerciseRow,
  WorkoutSetLogRow,
} from "@/types/database.types";
